"""add entityes

Revision ID: 081b42c605be
Revises: 2409af6e6222
Create Date: 2024-03-05 00:33:38.680918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081b42c605be'
down_revision: Union[str, None] = '2409af6e6222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('count_employees', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('doctors', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False)
    op.create_foreign_key(None, 'doctors', 'hospital', ['hospital_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_doctors_hospital_id'), table_name='doctors')
    op.drop_column('doctors', 'hospital_id')
    op.drop_table('hospital')
    # ### end Alembic commands ###
