"""add entityes

Revision ID: 7bcfced2d09a
Revises: 1ffc162fa20c
Create Date: 2024-03-12 18:26:54.311925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcfced2d09a'
down_revision: Union[str, None] = '1ffc162fa20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('patients_new')
    op.add_column('doctors', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_doctors_university_id'), 'doctors', ['university_id'], unique=False)
    op.create_foreign_key(None, 'doctors', 'university', ['university_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_doctors_university_id'), table_name='doctors')
    op.drop_column('doctors', 'university_id')
    op.create_table('patients_new',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], name='fk_patients', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'first_name', 'last_name', 'age', name='patients_new_pkey')
    )
    op.drop_table('university')
    # ### end Alembic commands ###
