"""add entityes

Revision ID: c45777d436f1
Revises: 46de56baee47
Create Date: 2024-03-05 00:38:08.030842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45777d436f1'
down_revision: Union[str, None] = '46de56baee47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistic_company_new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_types', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logistic_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('logistic_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['logistic_company_id'], ['logistic_company_new.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_company_hospital_id'), 'logistic_company', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_logistic_company_logistic_company_id'), 'logistic_company', ['logistic_company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistic_company_logistic_company_id'), table_name='logistic_company')
    op.drop_index(op.f('ix_logistic_company_hospital_id'), table_name='logistic_company')
    op.drop_table('logistic_company')
    op.drop_table('logistic_company_new')
    # ### end Alembic commands ###
